version: 2
updates:
  # Rust dependencies (Cargo.toml/Cargo.lock)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        directory: "/fixtures/*"
      - dependency-name: "*"
        directory: "/benchmarks/*"
    groups:
      python-dependencies:
        patterns:
          - "*"
