name: Test Windows Build 
on: push

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  
  build-python-wheels-windows:
    name: Build Python Wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1.49.4
        with:
          command: build
          args: --release --features python --out dist -i ${{ matrix.python }}
          sccache: "true"
          manylinux: auto

